export enum ContractErrorCode {
  GrantNotFound = 1,
  Unauthorized = 2,
  MilestoneAlreadyApproved = 3,
  QuorumNotReached = 4,
  DeadlinePassed = 5,
  InvalidInput = 6,
  MilestoneNotSubmitted = 7,
  AlreadyVoted = 8,
  MilestoneNotFound = 9,
  InvalidState = 10,
  NoRefundableAmount = 11,
  NotAllMilestonesApproved = 12,
  AlreadyRegistered = 13,
  MilestoneAlreadySubmitted = 14,
  InsufficientStake = 15,
  StakeNotFound = 16,
  NotVerified = 17,
  BatchEmpty = 18,
  BatchTooLarge = 19,
  ReentrancyDetected = 20,
  NotMultisigSigner = 21,
  AlreadySignedRelease = 22,
  ReleaseNotReady = 23,
  GrantAlreadyReleased = 24,
  InsufficientReputation = 25,
  CommunityReviewPeriod = 26,
  AlreadyUpvoted = 27,
  CancellationGracePeriod = 28,
  HeartbeatMissed = 29,
  Blacklisted = 30,
  NotContractAdmin = 31,
  InsufficientBalance = 32,
  ContractPaused = 33,
  CapReached = 34,
  TooManyTags = 35,
  TagTooLong = 36,
  DisputeFeeInsufficient = 37,
  DisputeAlreadyCharged = 38,
  ExtensionDenied = 39,
  DeadlineNotSet = 40,
  ExpiryNotReached = 41,
  RoleAlreadyAssigned = 42,
  RoleNotAssigned = 43,
  HeartbeatNotStale = 44,
  DuplicateBountySubmitter = 45,
  ContributorProfileRequired = 46,
  BountySubmissionsCap = 47,
  InvalidTokenInterface = 48,
}

export const ErrorMessages: Record<ContractErrorCode, string> = {
  [ContractErrorCode.GrantNotFound]: "The specified grant was not found.",
  [ContractErrorCode.Unauthorized]: "You are not authorized to perform this action.",
  [ContractErrorCode.MilestoneAlreadyApproved]: "This milestone has already been approved.",
  [ContractErrorCode.QuorumNotReached]: "The required quorum of reviewers has not been reached.",
  [ContractErrorCode.DeadlinePassed]: "The deadline for this operation has already passed.",
  [ContractErrorCode.InvalidInput]: "The provided input is invalid.",
  [ContractErrorCode.MilestoneNotSubmitted]: "The milestone has not been submitted yet.",
  [ContractErrorCode.AlreadyVoted]: "You have already cast your vote.",
  [ContractErrorCode.MilestoneNotFound]: "The specified milestone was not found.",
  [ContractErrorCode.InvalidState]: "The grant or milestone is in an invalid state for this operation.",
  [ContractErrorCode.NoRefundableAmount]: "There is no refundable amount available.",
  [ContractErrorCode.NotAllMilestonesApproved]: "All milestones must be approved before this action.",
  [ContractErrorCode.AlreadyRegistered]: "The contributor is already registered.",
  [ContractErrorCode.MilestoneAlreadySubmitted]: "The milestone has already been submitted.",
  [ContractErrorCode.InsufficientStake]: "Insufficient stake to perform this action.",
  [ContractErrorCode.StakeNotFound]: "Reviewer stake not found.",
  [ContractErrorCode.NotVerified]: "The user is not verified.",
  [ContractErrorCode.BatchEmpty]: "The provided batch is empty.",
  [ContractErrorCode.BatchTooLarge]: "The provided batch is too large.",
  [ContractErrorCode.ReentrancyDetected]: "Security error: reentrancy detected.",
  [ContractErrorCode.NotMultisigSigner]: "You are not an authorized multisig signer for this grant.",
  [ContractErrorCode.AlreadySignedRelease]: "You have already signed the release for this grant.",
  [ContractErrorCode.ReleaseNotReady]: "The grant release is not ready yet.",
  [ContractErrorCode.GrantAlreadyReleased]: "The grant has already been released.",
  [ContractErrorCode.InsufficientReputation]: "Your reputation score is too low for this action.",
  [ContractErrorCode.CommunityReviewPeriod]: "The community review period has not elapsed yet.",
  [ContractErrorCode.AlreadyUpvoted]: "You have already upvoted this milestone.",
  [ContractErrorCode.CancellationGracePeriod]: "The cancellation grace period has not elapsed yet.",
  [ContractErrorCode.HeartbeatMissed]: "The grant is inactive due to missed heartbeats.",
  [ContractErrorCode.Blacklisted]: "This address has been blacklisted.",
  [ContractErrorCode.NotContractAdmin]: "Caller is not the contract global admin.",
  [ContractErrorCode.InsufficientBalance]: "Insufficient token balance in escrow or wallet.",
  [ContractErrorCode.ContractPaused]: "The contract is currently paused.",
  [ContractErrorCode.CapReached]: "The grant's funding cap has been reached.",
  [ContractErrorCode.TooManyTags]: "The grant has too many tags (max 5).",
  [ContractErrorCode.TagTooLong]: "A tag exceeds the 20-character limit.",
  [ContractErrorCode.DisputeFeeInsufficient]: "Insufficient balance to pay the dispute fee.",
  [ContractErrorCode.DisputeAlreadyCharged]: "Dispute fee has already been charged for this milestone.",
  [ContractErrorCode.ExtensionDenied]: "The milestone extension request was denied.",
  [ContractErrorCode.DeadlineNotSet]: "The milestone deadline has not been set.",
  [ContractErrorCode.ExpiryNotReached]: "The milestone expiry has not been reached yet.",
  [ContractErrorCode.RoleAlreadyAssigned]: "The role has already been assigned to this account.",
  [ContractErrorCode.RoleNotAssigned]: "The account does not have the specified role.",
  [ContractErrorCode.HeartbeatNotStale]: "The heartbeat is not stale enough for this operation.",
  [ContractErrorCode.DuplicateBountySubmitter]: "A submission from this contributor already exists.",
  [ContractErrorCode.ContributorProfileRequired]: "A registered contributor profile is required.",
  [ContractErrorCode.BountySubmissionsCap]: "The maximum number of bounty submissions has been reached.",
  [ContractErrorCode.InvalidTokenInterface]: "The token does not implement the required interface.",
};
